export {
  type ActiveLocalEmbeddingModel,
  deleteLocalModel,
  downloadModel,
  embedBatchLocal,
  embedQueryLocal,
  embedTextLocal,
  getLocalEmbeddingModel,
  getLocalModelFiles,
  isLocalModelReady,
  isTransformersAvailable,
  LOCAL_EMBEDDING_MODELS,
  type LocalEmbeddingFamily,
  type ModelFileInfo,
  type ModelFileProgress,
  resetPipeline,
} from './local.js'

export {
  embedBatch,
  EMBEDDING_DIM,
  type EmbeddingLocalFamily,
  type EmbeddingProvider,
  type EmbeddingSelection,
  embedPassage,
  embedQuery,
  embedText,
  getActiveEmbeddingSelection,
  getEmbeddingProvider,
  getLocalEmbeddingModelFamily,
  isEmbeddingConfigured,
  setEmbeddingProvider,
  setLocalEmbeddingModelFamily,
} from './provider.js'
