export { default as CommandPalette } from './components/CommandPalette.vue'
export { default as ContextMenu } from './components/ContextMenu.vue'
export type { ContextMenuItem } from './components/ContextMenu.vue'
export type { CommandGroup, CommandItem } from './components/CommandPalette.vue'
export { default as DirectoryBrowserModal } from './components/DirectoryBrowserModal.vue'
// Re-export component prop types
export type { DirectoryBrowserEntry } from './components/DirectoryBrowserModal.vue'
export { default as DirectoryPicker } from './components/DirectoryPicker.vue'
export type { DirectoryPickerEntry, DirectorySelection } from './components/DirectoryPicker.vue'
// Components
export { default as Dropdown } from './components/Dropdown.vue'
export type { DropdownItem } from './components/Dropdown.vue'
export { default as FileTree } from './components/FileTree.vue'
export type { FileTreeNode } from './components/FileTree.vue'
export { default as ImageAttachmentStrip } from './components/ImageAttachmentStrip.vue'
export type { ImageAttachmentStripItem } from './components/ImageAttachmentStrip.vue'
export { default as List, type ListItemSelectMode } from './components/List.vue'
export { default as ListItem, type ListItemAction } from './components/ListItem.vue'
export { default as Modal } from './components/Modal.vue'
export { default as Select } from './components/Select.vue'
export type { SelectOption } from './components/Select.vue'

export { default as Switch } from './components/Switch.vue'
export { default as ToastContainer } from './components/ToastContainer.vue'
export { default as Tooltip } from './components/Tooltip.vue'
export { default as Tree } from './components/Tree.vue'
export type { FlatTreeNode, TreeNode } from './components/Tree.vue'
export { default as VirtualList } from './components/VirtualList.vue'

// Composables
export { useToast } from './composables/useToast'
export type { ConfirmOptions, PromptOptions, Toast, ToastType } from './composables/useToast'
